package Albero;

public class Constant {

    public static final String
            EXPR_OP = "Expr",
            WHILE_STAT_OP = "WhileStat",
            ELIF_OP = "Elif",
            IF_STAT_OP = "IfStat",
            CALL_PROC_OP = "CallProc",
            ASSIGN_OP = "AssignStat",
            PROC_OP = "ProcOp",
            DECL_OP = "DeclOp",
            WRITE_OP = "WriteStat",
            PROGRAM_NODE = "ProgramOp",
            VAR_DECL_NODE = "VarDeclOp",
            EXPR_DECL_NODE = "ExprDeclNode",
            RES_TYPE_LIST = "ResultTypeList",
            RET_EXPR = "ReturnExpression",
            PARAM_DEC_LIST = "ParamDecList",
            ID_LIST="IdList",
            RES_TYPE="ResultType",
            ID_LIST_OP = "IdListOp",
            STAT_LIST_OP ="StatList",
            STAT_OP="Stat",
            ELIF_LIST_OP="ElifList",
            EMPTY="Empty",
            READ_OP="ReadLnStat",
            INT_CONST="INT_CONST",
            FLOAT_CONST="FLOAT_CONST",
            STRING_CONST="STRING_CONST",
            BOOL_CONST="BOOLE",
            ID_CONST="ID",
            ELSE_OP="Else",
            PROC_LIST="ProcList",
            SUM_OP="SUM_OP",
            DIFF_OP="DIFF_OP",
            MUL_OP="MUL_OP",
            DIV_OP="DIV_OP",
            AND_OP="AND_OP",
            OR_OP="OR_OP",
            GT_OP="GT_OP",
            GE_OP="GE_OP",
            LT_OP="LT_OP",
            LE_OP="LE_OP",
            EQ_OP="EQ_OP",
            NE_OP="NE_OP",
            MINUS_OP="MINUS_OP",
            NOT_OP="NOT_OP",
            NULL_CONST="NULL_CONST";

}
